### ISSUE TITLE
Object Id displayed when lookup field included in fieldset

### ISSUE THREAD

**Issue by user851** [Simran-Sohal/Ligthning-Components#1]
When using a lookup field in the fieldset the lookup **object Id** is displayed in the output rather than the lookup **object name**. This is different to the behaviour of a native lightning component that will display the lookup object name when the lookup field is placed on the page.

**Comment by Simran-Sohal** [comment]
@user851 ... Yes the current version does not support the lookup/reference fields. This will be available in the next version. (Expected Next Version release date : 17 Jul)

**Comment by SFDC201** [comment]
I am using this component and following the same step which is written in the guide but when i am using it in my org it is showing nothing. I think I am missing fieldsetname I am not able to find out that where we will write our **Fieldset** name. My fieldset name is accountfieldset. Please help on it.

**Comment by Simran-Sohal** [comment]
@SFDC201 ... when you drag the component to your lightning record page, you can see the component properties on the right side of the Lightning App Builder. Enter the Field Set name (API Name) there.

<img width="1436" alt="screen shot 2017-07-13 at 1 35 28 pm" src="https://user-images.githubusercontent.com/17467143/28149347-356f81e0-67d0-11e7-8a4b-4c9b9d45dd44.png">

**Comment by Simran-Sohal** [comment]
@user851  @SFDC201 
I have modified the contents of the repo. Existing components/classes are modified. New component referenceField has been added. Please use the current version.
- Handles the lookup/reference fields
- Open the reference record on click
- Displays the label for the picklist fields.

**Comment by Simran-Sohal** [comment]
This component has been released via AppExchange
https://appexchange.salesforce.com/listingDetail?listingId=a0N3A00000ErEqoUAF

The AppExchange release also includes another component - Related Record Table

For latest version of the package please email support@financialspectra.com
