### ISSUE TITLE
Bug - 01 - Lookups Relationships

### ISSUE THREAD

**Issue by ghost** [Simran-Sohal/Ligthning-Components#2]

**Comment by ghost** [comment]
When we add lookup or any relationship in field set and then add that field set in your components in Lighting App Builder , after saving or activating on the layout it shows just id of that lookup field.

Can you see and let me know what can be the possible reason , its not working as a normal Lookup 

Thanks

Paarth Jolly 
Skype - Parthjolly

**Comment by Simran-Sohal** [comment]
@Webothcode Did you install the package? if yes, please install the the latest version.
Here is the link:
https://login.salesforce.com/packaging/installPackage.apexp?p0=04t6A000001KtRb

**Comment by ghost** [comment]
After updating the Package still I have the same issue that Id comes instead of Lookup Relationship

**Comment by Webothcode** [comment]
![screen shot 2017-07-18 at 4 30 55 pm](https://user-images.githubusercontent.com/27613522/28313979-81b6c5e0-6bd6-11e7-98b6-c3923b302a3b.png)

**Comment by ghost** [comment]
![bug 1](https://user-images.githubusercontent.com/27613522/28314220-46253524-6bd7-11e7-9be6-bc79002a8825.png)

**Comment by Simran-Sohal** [comment]
@Webothcode ... I can't find the issue at my end. Please try the follow steps
1. Remove the component from your layout 
2. Uninstall the Prizm Lightning package from your org
3. Reinstall the latest version again
4. Add the component to your lightning page
5. Verify the output

Here is what I see internally in my org. (See the Owner Id field)
<img width="864" alt="screen shot 2017-07-19 at 10 41 54 am" src="https://user-images.githubusercontent.com/17467143/28345724-5e07bad4-6c6f-11e7-8661-1a1235f6ac9c.png">

If you still face an issue, send me your contact email. We can setup a call to debug your issue.

**Comment by Simran-Sohal** [comment]
@Webothcode ... I have tested the above mentioned approach. It works.

Looks like some issue with the package upgrade. I am raising this issue with Salesforce.

If the component is helpful, please provide your comment on the AppExchange publishing and a star on this repository.

**Comment by ghost** [comment]
I guess it should Uninstall it and then maybe it would work.
Also I have a question about one more things that , when we edit the page , any way that only the selected section comes up for editing instead of whole page .

Thanks

**Comment by Simran-Sohal** [comment]
@Webothcode ... that is not supported by the Lightning App Builder.
